data_ingestion_config:
  zip_file_url: "https://drive.google.com/file/d/1wtuYCf_mUdFMYGGKk8D_YVTodQA6BI-J/view?usp=sharing"
  zip_file_name: "dataset.zip"


data_transformation_config:
  img_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  degree_n: -20
  degree_p: +20
  train_ratio: 0.7
  valid_ratio: 0.2


model_trainer_config:
  epochs: 5
  lr: 0.0001
  batch_size: 32
  num_workers: 4

model_evaluation_config:
  batch_size: 32
  num_workers: 4
  model_repo_name: "z4hid/xray-vision"


prediction_pipeline_config:
  input_image: input.jpg
  model_repo_name: "z4hid/xray-vision"
  model_name: model.pt
  threshold: 0.5