data_ingestion_config:
  zip_file_url: "https://drive.google.com/file/d/1lX-4VeIqJaS82ESmNnSTqQnBM6tS7-ic/view?usp=sharing"
  zip_file_name: "data.zip"


data_transformation_config:
  img_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  degree_n: -20
  degree_p: +20
  train_ratio: 0.6
  valid_ratio: 0.3
